# Generated by Django 2.1.7 on 2019-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='attachment', to='mySite.Comment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='post',
            field=models.ManyToManyField(null=True, related_name='attachment', to='mySite.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
