# Generated by Django 2.1.7 on 2019-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0003_auto_20190331_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.ManyToManyField(related_name='comment', to='mySite.Attachment'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
