# Generated by Django 2.1.7 on 2019-05-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0006_auto_20190413_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='mySite.Attachment'),
            preserve_default=False,
        ),
    ]
